FROM python:3

WORKDIR /opt/workspace
COPY . .
RUN python -m pip install --upgrade pip

# setup venv path
ENV VENVPATH=/root/.local/.venv

# add convenient venv activate alias
RUN echo 'alias activate="source ${VENVPATH}/bin/activate"' >> ~/.bashrc

EXPOSE 5000