services:
    lib:
      container_name: katas-py
      build:
        context: ..
        dockerfile: docker/Dockerfile.dev
      entrypoint: sh -c "echo 'your custom command here' && tail -f /dev/null"
      ports:
        - "5000:5000"
      volumes:
        - ..:/opt/workspace
      working_dir: /opt/workspace
      stdin_open: true
      depends_on:
        - db
    db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      ports:
        - "5432:5432"
      volumes:
        - db:/var/lib/postgresql/data
        # Initial Query to build database tables and mock data
        - ../db/mock-create_tables.sql:/docker-entrypoint-initdb.d/create-tables-mock-data.sql
networks:
  overlay:
volumes:
  db:
    driver: local